// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package positions

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// SwitchMarginModeResp struct for SwitchMarginModeResp
type SwitchMarginModeResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
	Symbol string `json:"symbol,omitempty"`
	// Margin mode: ISOLATED (isolated), CROSS (cross margin).
	MarginMode string `json:"marginMode,omitempty"`
}

// NewSwitchMarginModeResp instantiates a new SwitchMarginModeResp object
// This constructor will assign default values to properties that have it defined
func NewSwitchMarginModeResp(symbol string, marginMode string) *SwitchMarginModeResp {
	this := SwitchMarginModeResp{}
	this.Symbol = symbol
	this.MarginMode = marginMode
	return &this
}

// NewSwitchMarginModeRespWithDefaults instantiates a new SwitchMarginModeResp object
// This constructor will only assign default values to properties that have it defined,
func NewSwitchMarginModeRespWithDefaults() *SwitchMarginModeResp {
	this := SwitchMarginModeResp{}
	return &this
}

func (o *SwitchMarginModeResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["marginMode"] = o.MarginMode
	return toSerialize
}

func (o *SwitchMarginModeResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
