// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package positions

// GetPositionsHistoryReq struct for GetPositionsHistoryReq
type GetPositionsHistoryReq struct {
	// Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
	Symbol *string `json:"symbol,omitempty" url:"symbol,omitempty"`
	// Closing start time(ms)
	From *int64 `json:"from,omitempty" url:"from,omitempty"`
	// Closing end time(ms)
	To *int64 `json:"to,omitempty" url:"to,omitempty"`
	// Number of requests per page, max 200, default 10
	Limit *int32 `json:"limit,omitempty" url:"limit,omitempty"`
	// Current page number, default 1
	PageId *int32 `json:"pageId,omitempty" url:"pageId,omitempty"`
}

// NewGetPositionsHistoryReq instantiates a new GetPositionsHistoryReq object
// This constructor will assign default values to properties that have it defined
func NewGetPositionsHistoryReq() *GetPositionsHistoryReq {
	this := GetPositionsHistoryReq{}
	var limit int32 = 10
	this.Limit = &limit
	var pageId int32 = 1
	this.PageId = &pageId
	return &this
}

// NewGetPositionsHistoryReqWithDefaults instantiates a new GetPositionsHistoryReq object
// This constructor will only assign default values to properties that have it defined,
func NewGetPositionsHistoryReqWithDefaults() *GetPositionsHistoryReq {
	this := GetPositionsHistoryReq{}
	var limit int32 = 10
	this.Limit = &limit
	var pageId int32 = 1
	this.PageId = &pageId
	return &this
}

func (o *GetPositionsHistoryReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["limit"] = o.Limit
	toSerialize["pageId"] = o.PageId
	return toSerialize
}

type GetPositionsHistoryReqBuilder struct {
	obj *GetPositionsHistoryReq
}

func NewGetPositionsHistoryReqBuilder() *GetPositionsHistoryReqBuilder {
	return &GetPositionsHistoryReqBuilder{obj: NewGetPositionsHistoryReqWithDefaults()}
}

// Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
func (builder *GetPositionsHistoryReqBuilder) SetSymbol(value string) *GetPositionsHistoryReqBuilder {
	builder.obj.Symbol = &value
	return builder
}

// Closing start time(ms)
func (builder *GetPositionsHistoryReqBuilder) SetFrom(value int64) *GetPositionsHistoryReqBuilder {
	builder.obj.From = &value
	return builder
}

// Closing end time(ms)
func (builder *GetPositionsHistoryReqBuilder) SetTo(value int64) *GetPositionsHistoryReqBuilder {
	builder.obj.To = &value
	return builder
}

// Number of requests per page, max 200, default 10
func (builder *GetPositionsHistoryReqBuilder) SetLimit(value int32) *GetPositionsHistoryReqBuilder {
	builder.obj.Limit = &value
	return builder
}

// Current page number, default 1
func (builder *GetPositionsHistoryReqBuilder) SetPageId(value int32) *GetPositionsHistoryReqBuilder {
	builder.obj.PageId = &value
	return builder
}

func (builder *GetPositionsHistoryReqBuilder) Build() *GetPositionsHistoryReq {
	return builder.obj
}
