# Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

from abc import ABC, abstractmethod
from kucoin_universal_sdk.internal.interfaces.transport import Transport
from kucoin_universal_sdk.generate.viplending.viplending.api_vip_lending import VIPLendingAPI, VIPLendingAPIImpl


class VIPLendingService(ABC):

    @abstractmethod
    def get_vip_lending_api(self) -> VIPLendingAPI:
        """
        get VIPLendingAPI
        """
        pass


class VIPLendingServiceImpl(VIPLendingService):

    def __init__(self, transport: Transport):
        self.transport = transport
        self.vip_lending = VIPLendingAPIImpl(transport)

    def get_vip_lending_api(self) -> VIPLendingAPI:
        return self.vip_lending
