// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

// GetPremiumIndexDataList struct for GetPremiumIndexDataList
type GetPremiumIndexDataList struct {
	// Symbol of the contract, Please refer to [Get Symbol endpoint: premiumsSymbol1M, premiumsSymbol8H](https://www.kucoin.com/docs-new/api-3470220)
	Symbol string `json:"symbol,omitempty"`
	// Granularity(milisecond)
	Granularity int32 `json:"granularity,omitempty"`
	// Timestamp(milisecond)
	TimePoint int64 `json:"timePoint,omitempty"`
	// Premium index
	Value float32 `json:"value,omitempty"`
}

// NewGetPremiumIndexDataList instantiates a new GetPremiumIndexDataList object
// This constructor will assign default values to properties that have it defined
func NewGetPremiumIndexDataList(symbol string, granularity int32, timePoint int64, value float32) *GetPremiumIndexDataList {
	this := GetPremiumIndexDataList{}
	this.Symbol = symbol
	this.Granularity = granularity
	this.TimePoint = timePoint
	this.Value = value
	return &this
}

// NewGetPremiumIndexDataListWithDefaults instantiates a new GetPremiumIndexDataList object
// This constructor will only assign default values to properties that have it defined,
func NewGetPremiumIndexDataListWithDefaults() *GetPremiumIndexDataList {
	this := GetPremiumIndexDataList{}
	return &this
}

func (o *GetPremiumIndexDataList) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["granularity"] = o.Granularity
	toSerialize["timePoint"] = o.TimePoint
	toSerialize["value"] = o.Value
	return toSerialize
}
