// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package marginprivate

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// IsolatedMarginPositionEvent struct for IsolatedMarginPositionEvent
type IsolatedMarginPositionEvent struct {
	// common response
	CommonResponse *types.WsMessage
	// Isolated margin symbol
	Tag string `json:"tag,omitempty"`
	// Position status
	Status string `json:"status,omitempty"`
	// Status type
	StatusBizType string `json:"statusBizType,omitempty"`
	// Accumulated principal
	AccumulatedPrincipal string                                             `json:"accumulatedPrincipal,omitempty"`
	ChangeAssets         map[string]IsolatedMarginPositionChangeAssetsValue `json:"changeAssets,omitempty"`
	Timestamp            int64                                              `json:"timestamp,omitempty"`
}

// NewIsolatedMarginPositionEvent instantiates a new IsolatedMarginPositionEvent object
// This constructor will assign default values to properties that have it defined
func NewIsolatedMarginPositionEvent(tag string, status string, statusBizType string, accumulatedPrincipal string, changeAssets map[string]IsolatedMarginPositionChangeAssetsValue, timestamp int64) *IsolatedMarginPositionEvent {
	this := IsolatedMarginPositionEvent{}
	this.Tag = tag
	this.Status = status
	this.StatusBizType = statusBizType
	this.AccumulatedPrincipal = accumulatedPrincipal
	this.ChangeAssets = changeAssets
	this.Timestamp = timestamp
	return &this
}

// NewIsolatedMarginPositionEventWithDefaults instantiates a new IsolatedMarginPositionEvent object
// This constructor will only assign default values to properties that have it defined,
func NewIsolatedMarginPositionEventWithDefaults() *IsolatedMarginPositionEvent {
	this := IsolatedMarginPositionEvent{}
	return &this
}

func (o *IsolatedMarginPositionEvent) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["tag"] = o.Tag
	toSerialize["status"] = o.Status
	toSerialize["statusBizType"] = o.StatusBizType
	toSerialize["accumulatedPrincipal"] = o.AccumulatedPrincipal
	toSerialize["changeAssets"] = o.ChangeAssets
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize
}

type IsolatedMarginPositionEventCallback func(topic string, subject string, data *IsolatedMarginPositionEvent) error

type IsolatedMarginPositionEventCallbackWrapper struct {
	callback IsolatedMarginPositionEventCallback
}

func (w *IsolatedMarginPositionEventCallbackWrapper) OnMessage(msg *types.WsMessage) error {
	obj := &IsolatedMarginPositionEvent{}
	err := json.Unmarshal(msg.RawData, obj)
	if err != nil {
		return err
	}
	obj.CommonResponse = msg
	return w.callback(msg.Topic, msg.Subject, obj)
}
