// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package marginprivate

// CrossMarginPositionAssetListValue struct for CrossMarginPositionAssetListValue
type CrossMarginPositionAssetListValue struct {
	Total     string `json:"total,omitempty"`
	Available string `json:"available,omitempty"`
	Hold      string `json:"hold,omitempty"`
}

// NewCrossMarginPositionAssetListValue instantiates a new CrossMarginPositionAssetListValue object
// This constructor will assign default values to properties that have it defined
func NewCrossMarginPositionAssetListValue(total string, available string, hold string) *CrossMarginPositionAssetListValue {
	this := CrossMarginPositionAssetListValue{}
	this.Total = total
	this.Available = available
	this.Hold = hold
	return &this
}

// NewCrossMarginPositionAssetListValueWithDefaults instantiates a new CrossMarginPositionAssetListValue object
// This constructor will only assign default values to properties that have it defined,
func NewCrossMarginPositionAssetListValueWithDefaults() *CrossMarginPositionAssetListValue {
	this := CrossMarginPositionAssetListValue{}
	return &this
}

func (o *CrossMarginPositionAssetListValue) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["available"] = o.Available
	toSerialize["hold"] = o.Hold
	return toSerialize
}
