# coding: utf-8

# Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

from __future__ import annotations
import pprint
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from .model_get_all_tickers_ticker import GetAllTickersTicker
from kucoin_universal_sdk.internal.interfaces.response import Response
from kucoin_universal_sdk.model.common import RestResponse


class GetAllTickersResp(BaseModel, Response):
    """
    GetAllTickersResp

    Attributes:
        time (int): timestamp
        ticker (list[GetAllTickersTicker]): 
    """

    common_response: Optional[RestResponse] = Field(
        default=None, description="Common response")
    time: Optional[int] = Field(default=None, description="timestamp")
    ticker: Optional[List[GetAllTickersTicker]] = None

    __properties: ClassVar[List[str]] = ["time", "ticker"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=False,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_none=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[GetAllTickersResp]:
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        _dict = self.model_dump(
            by_alias=True,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ticker (list)
        _items = []
        if self.ticker:
            for _item_ticker in self.ticker:
                if _item_ticker:
                    _items.append(_item_ticker.to_dict())
            _dict['ticker'] = _items
        return _dict

    @classmethod
    def from_dict(
            cls, obj: Optional[Dict[str, Any]]) -> Optional[GetAllTickersResp]:
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "time":
            obj.get("time"),
            "ticker":
            [GetAllTickersTicker.from_dict(_item) for _item in obj["ticker"]]
            if obj.get("ticker") is not None else None
        })
        return _obj

    def set_common_response(self, response: RestResponse):
        self.common_response = response
