// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

// CancelOrderByClientOidReq struct for CancelOrderByClientOidReq
type CancelOrderByClientOidReq struct {
	// Client Order Id，unique identifier created by the user
	ClientOid *string `json:"clientOid,omitempty" path:"clientOid" url:"-"`
	// symbol
	Symbol *string `json:"symbol,omitempty" url:"symbol,omitempty"`
}

// NewCancelOrderByClientOidReq instantiates a new CancelOrderByClientOidReq object
// This constructor will assign default values to properties that have it defined
func NewCancelOrderByClientOidReq() *CancelOrderByClientOidReq {
	this := CancelOrderByClientOidReq{}
	return &this
}

// NewCancelOrderByClientOidReqWithDefaults instantiates a new CancelOrderByClientOidReq object
// This constructor will only assign default values to properties that have it defined,
func NewCancelOrderByClientOidReqWithDefaults() *CancelOrderByClientOidReq {
	this := CancelOrderByClientOidReq{}
	return &this
}

func (o *CancelOrderByClientOidReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["clientOid"] = o.ClientOid
	toSerialize["symbol"] = o.Symbol
	return toSerialize
}

type CancelOrderByClientOidReqBuilder struct {
	obj *CancelOrderByClientOidReq
}

func NewCancelOrderByClientOidReqBuilder() *CancelOrderByClientOidReqBuilder {
	return &CancelOrderByClientOidReqBuilder{obj: NewCancelOrderByClientOidReqWithDefaults()}
}

// Client Order Id，unique identifier created by the user
func (builder *CancelOrderByClientOidReqBuilder) SetClientOid(value string) *CancelOrderByClientOidReqBuilder {
	builder.obj.ClientOid = &value
	return builder
}

// symbol
func (builder *CancelOrderByClientOidReqBuilder) SetSymbol(value string) *CancelOrderByClientOidReqBuilder {
	builder.obj.Symbol = &value
	return builder
}

func (builder *CancelOrderByClientOidReqBuilder) Build() *CancelOrderByClientOidReq {
	return builder.obj
}
