// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// CancelOrderByOrderIdResp struct for CancelOrderByOrderIdResp
type CancelOrderByOrderIdResp struct {
	// common response
	CommonResponse *types.RestResponse
	// order id
	OrderId string `json:"orderId,omitempty"`
}

// NewCancelOrderByOrderIdResp instantiates a new CancelOrderByOrderIdResp object
// This constructor will assign default values to properties that have it defined
func NewCancelOrderByOrderIdResp(orderId string) *CancelOrderByOrderIdResp {
	this := CancelOrderByOrderIdResp{}
	this.OrderId = orderId
	return &this
}

// NewCancelOrderByOrderIdRespWithDefaults instantiates a new CancelOrderByOrderIdResp object
// This constructor will only assign default values to properties that have it defined,
func NewCancelOrderByOrderIdRespWithDefaults() *CancelOrderByOrderIdResp {
	this := CancelOrderByOrderIdResp{}
	return &this
}

func (o *CancelOrderByOrderIdResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	return toSerialize
}

func (o *CancelOrderByOrderIdResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
