// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package deposit

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetDepositHistoryResp struct for GetDepositHistoryResp
type GetDepositHistoryResp struct {
	// common response
	CommonResponse *types.RestResponse
	// current page
	CurrentPage int32 `json:"currentPage,omitempty"`
	// page size
	PageSize int32 `json:"pageSize,omitempty"`
	// total number
	TotalNum int32 `json:"totalNum,omitempty"`
	// total page
	TotalPage int32                    `json:"totalPage,omitempty"`
	Items     []GetDepositHistoryItems `json:"items,omitempty"`
}

// NewGetDepositHistoryResp instantiates a new GetDepositHistoryResp object
// This constructor will assign default values to properties that have it defined
func NewGetDepositHistoryResp(currentPage int32, pageSize int32, totalNum int32, totalPage int32, items []GetDepositHistoryItems) *GetDepositHistoryResp {
	this := GetDepositHistoryResp{}
	this.CurrentPage = currentPage
	this.PageSize = pageSize
	this.TotalNum = totalNum
	this.TotalPage = totalPage
	this.Items = items
	return &this
}

// NewGetDepositHistoryRespWithDefaults instantiates a new GetDepositHistoryResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetDepositHistoryRespWithDefaults() *GetDepositHistoryResp {
	this := GetDepositHistoryResp{}
	return &this
}

func (o *GetDepositHistoryResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["currentPage"] = o.CurrentPage
	toSerialize["pageSize"] = o.PageSize
	toSerialize["totalNum"] = o.TotalNum
	toSerialize["totalPage"] = o.TotalPage
	toSerialize["items"] = o.Items
	return toSerialize
}

func (o *GetDepositHistoryResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
