// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package debit

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// RepayResp struct for RepayResp
type RepayResp struct {
	// common response
	CommonResponse *types.RestResponse
	Timestamp      int64 `json:"timestamp,omitempty"`
	// Repay Order Id
	OrderNo string `json:"orderNo,omitempty"`
	// Actual repay amount
	ActualSize string `json:"actualSize,omitempty"`
}

// NewRepayResp instantiates a new RepayResp object
// This constructor will assign default values to properties that have it defined
func NewRepayResp(timestamp int64, orderNo string, actualSize string) *RepayResp {
	this := RepayResp{}
	this.Timestamp = timestamp
	this.OrderNo = orderNo
	this.ActualSize = actualSize
	return &this
}

// NewRepayRespWithDefaults instantiates a new RepayResp object
// This constructor will only assign default values to properties that have it defined,
func NewRepayRespWithDefaults() *RepayResp {
	this := RepayResp{}
	return &this
}

func (o *RepayResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["orderNo"] = o.OrderNo
	toSerialize["actualSize"] = o.ActualSize
	return toSerialize
}

func (o *RepayResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
