// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetServiceStatusResp struct for GetServiceStatusResp
type GetServiceStatusResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Status of service: open：normal transaction, close：Stop Trading/Maintenance, cancelonly：can only cancel the order but not place order
	Status string `json:"status,omitempty"`
	// Remark for operation
	Msg string `json:"msg,omitempty"`
}

// NewGetServiceStatusResp instantiates a new GetServiceStatusResp object
// This constructor will assign default values to properties that have it defined
func NewGetServiceStatusResp(status string, msg string) *GetServiceStatusResp {
	this := GetServiceStatusResp{}
	this.Status = status
	this.Msg = msg
	return &this
}

// NewGetServiceStatusRespWithDefaults instantiates a new GetServiceStatusResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetServiceStatusRespWithDefaults() *GetServiceStatusResp {
	this := GetServiceStatusResp{}
	return &this
}

func (o *GetServiceStatusResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["msg"] = o.Msg
	return toSerialize
}

func (o *GetServiceStatusResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
