// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

// GetAnnouncementsItems struct for GetAnnouncementsItems
type GetAnnouncementsItems struct {
	// Announcement ID
	AnnId int32 `json:"annId,omitempty"`
	// Announcement title
	AnnTitle string `json:"annTitle,omitempty"`
	// Announcement type
	AnnType []string `json:"annType,omitempty"`
	// Announcement description
	AnnDesc string `json:"annDesc,omitempty"`
	// Announcement release time, Unix millisecond timestamp format
	CTime int64 `json:"cTime,omitempty"`
	// language type
	Language string `json:"language,omitempty"`
	// Announcement link
	AnnUrl string `json:"annUrl,omitempty"`
}

// NewGetAnnouncementsItems instantiates a new GetAnnouncementsItems object
// This constructor will assign default values to properties that have it defined
func NewGetAnnouncementsItems(annId int32, annTitle string, annType []string, annDesc string, cTime int64, language string, annUrl string) *GetAnnouncementsItems {
	this := GetAnnouncementsItems{}
	this.AnnId = annId
	this.AnnTitle = annTitle
	this.AnnType = annType
	this.AnnDesc = annDesc
	this.CTime = cTime
	this.Language = language
	this.AnnUrl = annUrl
	return &this
}

// NewGetAnnouncementsItemsWithDefaults instantiates a new GetAnnouncementsItems object
// This constructor will only assign default values to properties that have it defined,
func NewGetAnnouncementsItemsWithDefaults() *GetAnnouncementsItems {
	this := GetAnnouncementsItems{}
	return &this
}

func (o *GetAnnouncementsItems) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["annId"] = o.AnnId
	toSerialize["annTitle"] = o.AnnTitle
	toSerialize["annType"] = o.AnnType
	toSerialize["annDesc"] = o.AnnDesc
	toSerialize["cTime"] = o.CTime
	toSerialize["language"] = o.Language
	toSerialize["annUrl"] = o.AnnUrl
	return toSerialize
}
