// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetTradeHistoryResp struct for GetTradeHistoryResp
type GetTradeHistoryResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetTradeHistoryData `json:"data,omitempty"`
}

// NewGetTradeHistoryResp instantiates a new GetTradeHistoryResp object
// This constructor will assign default values to properties that have it defined
func NewGetTradeHistoryResp(data []GetTradeHistoryData) *GetTradeHistoryResp {
	this := GetTradeHistoryResp{}
	this.Data = data
	return &this
}

// NewGetTradeHistoryRespWithDefaults instantiates a new GetTradeHistoryResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetTradeHistoryRespWithDefaults() *GetTradeHistoryResp {
	this := GetTradeHistoryResp{}
	return &this
}

func (o *GetTradeHistoryResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetTradeHistoryResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetTradeHistoryResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
