// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// Get24hrStatsResp struct for Get24hrStatsResp
type Get24hrStatsResp struct {
	// common response
	CommonResponse *types.RestResponse
	// timestamp
	Time int64 `json:"time,omitempty"`
	// Symbol
	Symbol string `json:"symbol,omitempty"`
	// Best bid price
	Buy string `json:"buy,omitempty"`
	// Best ask price
	Sell string `json:"sell,omitempty"`
	// 24h change rate
	ChangeRate string `json:"changeRate,omitempty"`
	// 24h change price
	ChangePrice string `json:"changePrice,omitempty"`
	// Highest price in 24h
	High string `json:"high,omitempty"`
	// Lowest price in 24h
	Low string `json:"low,omitempty"`
	// 24h volume, executed based on base currency
	Vol string `json:"vol,omitempty"`
	// 24h traded amount
	VolValue string `json:"volValue,omitempty"`
	// Last traded price
	Last string `json:"last,omitempty"`
	// Average trading price in the last 24 hours
	AveragePrice string `json:"averagePrice,omitempty"`
	// Basic Taker Fee
	TakerFeeRate string `json:"takerFeeRate,omitempty"`
	// Basic Maker Fee
	MakerFeeRate string `json:"makerFeeRate,omitempty"`
	// The taker fee coefficient. The actual fee needs to be multiplied by this coefficient to get the final fee. Most currencies have a coefficient of 1. If set to 0, it means no fee
	TakerCoefficient string `json:"takerCoefficient,omitempty"`
	// The maker fee coefficient. The actual fee needs to be multiplied by this coefficient to get the final fee. Most currencies have a coefficient of 1. If set to 0, it means no fee
	MakerCoefficient string `json:"makerCoefficient,omitempty"`
}

// NewGet24hrStatsResp instantiates a new Get24hrStatsResp object
// This constructor will assign default values to properties that have it defined
func NewGet24hrStatsResp(time int64, symbol string, buy string, sell string, changeRate string, changePrice string, high string, low string, vol string, volValue string, last string, averagePrice string, takerFeeRate string, makerFeeRate string, takerCoefficient string, makerCoefficient string) *Get24hrStatsResp {
	this := Get24hrStatsResp{}
	this.Time = time
	this.Symbol = symbol
	this.Buy = buy
	this.Sell = sell
	this.ChangeRate = changeRate
	this.ChangePrice = changePrice
	this.High = high
	this.Low = low
	this.Vol = vol
	this.VolValue = volValue
	this.Last = last
	this.AveragePrice = averagePrice
	this.TakerFeeRate = takerFeeRate
	this.MakerFeeRate = makerFeeRate
	this.TakerCoefficient = takerCoefficient
	this.MakerCoefficient = makerCoefficient
	return &this
}

// NewGet24hrStatsRespWithDefaults instantiates a new Get24hrStatsResp object
// This constructor will only assign default values to properties that have it defined,
func NewGet24hrStatsRespWithDefaults() *Get24hrStatsResp {
	this := Get24hrStatsResp{}
	return &this
}

func (o *Get24hrStatsResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["time"] = o.Time
	toSerialize["symbol"] = o.Symbol
	toSerialize["buy"] = o.Buy
	toSerialize["sell"] = o.Sell
	toSerialize["changeRate"] = o.ChangeRate
	toSerialize["changePrice"] = o.ChangePrice
	toSerialize["high"] = o.High
	toSerialize["low"] = o.Low
	toSerialize["vol"] = o.Vol
	toSerialize["volValue"] = o.VolValue
	toSerialize["last"] = o.Last
	toSerialize["averagePrice"] = o.AveragePrice
	toSerialize["takerFeeRate"] = o.TakerFeeRate
	toSerialize["makerFeeRate"] = o.MakerFeeRate
	toSerialize["takerCoefficient"] = o.TakerCoefficient
	toSerialize["makerCoefficient"] = o.MakerCoefficient
	return toSerialize
}

func (o *Get24hrStatsResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
