// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package futurespublic

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// OrderbookLevel5Event struct for OrderbookLevel5Event
type OrderbookLevel5Event struct {
	// common response
	CommonResponse *types.WsMessage
	Bids           [][]interface{} `json:"bids,omitempty"`
	Sequence       int64           `json:"sequence,omitempty"`
	Timestamp      int64           `json:"timestamp,omitempty"`
	Ts             int64           `json:"ts,omitempty"`
	Asks           [][]interface{} `json:"asks,omitempty"`
}

// NewOrderbookLevel5Event instantiates a new OrderbookLevel5Event object
// This constructor will assign default values to properties that have it defined
func NewOrderbookLevel5Event(bids [][]interface{}, sequence int64, timestamp int64, ts int64, asks [][]interface{}) *OrderbookLevel5Event {
	this := OrderbookLevel5Event{}
	this.Bids = bids
	this.Sequence = sequence
	this.Timestamp = timestamp
	this.Ts = ts
	this.Asks = asks
	return &this
}

// NewOrderbookLevel5EventWithDefaults instantiates a new OrderbookLevel5Event object
// This constructor will only assign default values to properties that have it defined,
func NewOrderbookLevel5EventWithDefaults() *OrderbookLevel5Event {
	this := OrderbookLevel5Event{}
	return &this
}

func (o *OrderbookLevel5Event) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["bids"] = o.Bids
	toSerialize["sequence"] = o.Sequence
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["ts"] = o.Ts
	toSerialize["asks"] = o.Asks
	return toSerialize
}

type OrderbookLevel5EventCallback func(topic string, subject string, data *OrderbookLevel5Event) error

type OrderbookLevel5EventCallbackWrapper struct {
	callback OrderbookLevel5EventCallback
}

func (w *OrderbookLevel5EventCallbackWrapper) OnMessage(msg *types.WsMessage) error {
	obj := &OrderbookLevel5Event{}
	err := json.Unmarshal(msg.RawData, obj)
	if err != nil {
		return err
	}
	obj.CommonResponse = msg
	return w.callback(msg.Topic, msg.Subject, obj)
}
