// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package futures

// AddIsolatedMarginReq struct for AddIsolatedMarginReq
type AddIsolatedMarginReq struct {
	// Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
	Symbol string `json:"symbol,omitempty"`
	// Margin amount (min. margin amount≥0.00001667XBT）
	Margin float32 `json:"margin,omitempty"`
	// A unique ID generated by the user, to ensure the operation is processed by the system only once, The maximum length cannot exceed 36
	BizNo string `json:"bizNo,omitempty"`
}

// NewAddIsolatedMarginReq instantiates a new AddIsolatedMarginReq object
// This constructor will assign default values to properties that have it defined
func NewAddIsolatedMarginReq(symbol string, margin float32, bizNo string) *AddIsolatedMarginReq {
	this := AddIsolatedMarginReq{}
	this.Symbol = symbol
	this.Margin = margin
	this.BizNo = bizNo
	return &this
}

// NewAddIsolatedMarginReqWithDefaults instantiates a new AddIsolatedMarginReq object
// This constructor will only assign default values to properties that have it defined,
func NewAddIsolatedMarginReqWithDefaults() *AddIsolatedMarginReq {
	this := AddIsolatedMarginReq{}
	return &this
}

func (o *AddIsolatedMarginReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["margin"] = o.Margin
	toSerialize["bizNo"] = o.BizNo
	return toSerialize
}

type AddIsolatedMarginReqBuilder struct {
	obj *AddIsolatedMarginReq
}

func NewAddIsolatedMarginReqBuilder() *AddIsolatedMarginReqBuilder {
	return &AddIsolatedMarginReqBuilder{obj: NewAddIsolatedMarginReqWithDefaults()}
}

// Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
func (builder *AddIsolatedMarginReqBuilder) SetSymbol(value string) *AddIsolatedMarginReqBuilder {
	builder.obj.Symbol = value
	return builder
}

// Margin amount (min. margin amount≥0.00001667XBT）
func (builder *AddIsolatedMarginReqBuilder) SetMargin(value float32) *AddIsolatedMarginReqBuilder {
	builder.obj.Margin = value
	return builder
}

// A unique ID generated by the user, to ensure the operation is processed by the system only once, The maximum length cannot exceed 36
func (builder *AddIsolatedMarginReqBuilder) SetBizNo(value string) *AddIsolatedMarginReqBuilder {
	builder.obj.BizNo = value
	return builder
}

func (builder *AddIsolatedMarginReqBuilder) Build() *AddIsolatedMarginReq {
	return builder.obj
}
