// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package fee

import (
	"context"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/internal/interfaces"
)

type FeeAPI interface {

	// GetBasicFee Get Basic Fee - Spot/Margin
	// Description: This interface is for the spot/margin basic fee rate of users
	// +---------------------+---------+
	// | Extra API Info      | Value   |
	// +---------------------+---------+
	// | API-DOMAIN          | SPOT    |
	// | API-CHANNEL         | PRIVATE |
	// | API-PERMISSION      | GENERAL |
	// | API-RATE-LIMIT-POOL | SPOT    |
	// | API-RATE-LIMIT      | 3       |
	// +---------------------+---------+
	GetBasicFee(req *GetBasicFeeReq, ctx context.Context) (*GetBasicFeeResp, error)

	// GetSpotActualFee Get Actual Fee - Spot/Margin
	// Description: This interface is for the actual fee rate of the trading pair. You can inquire about fee rates of 10 trading pairs each time at most. The fee rate of your sub-account is the same as that of the master account.
	// +---------------------+---------+
	// | Extra API Info      | Value   |
	// +---------------------+---------+
	// | API-DOMAIN          | SPOT    |
	// | API-CHANNEL         | PRIVATE |
	// | API-PERMISSION      | GENERAL |
	// | API-RATE-LIMIT-POOL | SPOT    |
	// | API-RATE-LIMIT      | 3       |
	// +---------------------+---------+
	GetSpotActualFee(req *GetSpotActualFeeReq, ctx context.Context) (*GetSpotActualFeeResp, error)

	// GetFuturesActualFee Get Actual Fee - Futures
	// Description: This interface is for the actual futures fee rate of the trading pair. The fee rate of your sub-account is the same as that of the master account.
	// +---------------------+---------+
	// | Extra API Info      | Value   |
	// +---------------------+---------+
	// | API-DOMAIN          | FUTURES |
	// | API-CHANNEL         | PRIVATE |
	// | API-PERMISSION      | GENERAL |
	// | API-RATE-LIMIT-POOL | FUTURES |
	// | API-RATE-LIMIT      | 3       |
	// +---------------------+---------+
	GetFuturesActualFee(req *GetFuturesActualFeeReq, ctx context.Context) (*GetFuturesActualFeeResp, error)
}

type FeeAPIImpl struct {
	transport interfaces.Transport
}

func NewFeeAPIImp(transport interfaces.Transport) *FeeAPIImpl {
	return &FeeAPIImpl{transport: transport}
}

func (impl *FeeAPIImpl) GetBasicFee(req *GetBasicFeeReq, ctx context.Context) (*GetBasicFeeResp, error) {
	resp := &GetBasicFeeResp{}
	err := impl.transport.Call(ctx, "spot", false, "Get", "/api/v1/base-fee", req, resp, false)
	return resp, err
}

func (impl *FeeAPIImpl) GetSpotActualFee(req *GetSpotActualFeeReq, ctx context.Context) (*GetSpotActualFeeResp, error) {
	resp := &GetSpotActualFeeResp{}
	err := impl.transport.Call(ctx, "spot", false, "Get", "/api/v1/trade-fees", req, resp, false)
	return resp, err
}

func (impl *FeeAPIImpl) GetFuturesActualFee(req *GetFuturesActualFeeReq, ctx context.Context) (*GetFuturesActualFeeResp, error) {
	resp := &GetFuturesActualFeeResp{}
	err := impl.transport.Call(ctx, "futures", false, "Get", "/api/v1/trade-fees", req, resp, false)
	return resp, err
}
