// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package fee

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetFuturesActualFeeResp struct for GetFuturesActualFeeResp
type GetFuturesActualFeeResp struct {
	// common response
	CommonResponse *types.RestResponse
	// The unique identity of the trading pair and will not change even if the trading pair is renamed
	Symbol string `json:"symbol,omitempty"`
	// Actual taker fee rate of the trading pair
	TakerFeeRate string `json:"takerFeeRate,omitempty"`
	// Actual maker fee rate of the trading pair
	MakerFeeRate string `json:"makerFeeRate,omitempty"`
}

// NewGetFuturesActualFeeResp instantiates a new GetFuturesActualFeeResp object
// This constructor will assign default values to properties that have it defined
func NewGetFuturesActualFeeResp(symbol string, takerFeeRate string, makerFeeRate string) *GetFuturesActualFeeResp {
	this := GetFuturesActualFeeResp{}
	this.Symbol = symbol
	this.TakerFeeRate = takerFeeRate
	this.MakerFeeRate = makerFeeRate
	return &this
}

// NewGetFuturesActualFeeRespWithDefaults instantiates a new GetFuturesActualFeeResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetFuturesActualFeeRespWithDefaults() *GetFuturesActualFeeResp {
	this := GetFuturesActualFeeResp{}
	return &this
}

func (o *GetFuturesActualFeeResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["takerFeeRate"] = o.TakerFeeRate
	toSerialize["makerFeeRate"] = o.MakerFeeRate
	return toSerialize
}

func (o *GetFuturesActualFeeResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
