// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package withdrawal

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// WithdrawalV3Resp struct for WithdrawalV3Resp
type WithdrawalV3Resp struct {
	// common response
	CommonResponse *types.RestResponse
	// Withdrawal id, a unique ID for a withdrawal
	WithdrawalId string `json:"withdrawalId,omitempty"`
}

// NewWithdrawalV3Resp instantiates a new WithdrawalV3Resp object
// This constructor will assign default values to properties that have it defined
func NewWithdrawalV3Resp(withdrawalId string) *WithdrawalV3Resp {
	this := WithdrawalV3Resp{}
	this.WithdrawalId = withdrawalId
	return &this
}

// NewWithdrawalV3RespWithDefaults instantiates a new WithdrawalV3Resp object
// This constructor will only assign default values to properties that have it defined,
func NewWithdrawalV3RespWithDefaults() *WithdrawalV3Resp {
	this := WithdrawalV3Resp{}
	return &this
}

func (o *WithdrawalV3Resp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["withdrawalId"] = o.WithdrawalId
	return toSerialize
}

func (o *WithdrawalV3Resp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
