// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package earn

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetETHStakingProductsResp struct for GetETHStakingProductsResp
type GetETHStakingProductsResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetETHStakingProductsData `json:"data,omitempty"`
}

// NewGetETHStakingProductsResp instantiates a new GetETHStakingProductsResp object
// This constructor will assign default values to properties that have it defined
func NewGetETHStakingProductsResp(data []GetETHStakingProductsData) *GetETHStakingProductsResp {
	this := GetETHStakingProductsResp{}
	this.Data = data
	return &this
}

// NewGetETHStakingProductsRespWithDefaults instantiates a new GetETHStakingProductsResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetETHStakingProductsRespWithDefaults() *GetETHStakingProductsResp {
	this := GetETHStakingProductsResp{}
	return &this
}

func (o *GetETHStakingProductsResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetETHStakingProductsResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetETHStakingProductsResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
