// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package earn

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetAccountHoldingResp struct for GetAccountHoldingResp
type GetAccountHoldingResp struct {
	// common response
	CommonResponse *types.RestResponse
	// total number
	TotalNum int32                    `json:"totalNum,omitempty"`
	Items    []GetAccountHoldingItems `json:"items,omitempty"`
	// current page
	CurrentPage int32 `json:"currentPage,omitempty"`
	// page size
	PageSize int32 `json:"pageSize,omitempty"`
	// total page
	TotalPage int32 `json:"totalPage,omitempty"`
}

// NewGetAccountHoldingResp instantiates a new GetAccountHoldingResp object
// This constructor will assign default values to properties that have it defined
func NewGetAccountHoldingResp(totalNum int32, items []GetAccountHoldingItems, currentPage int32, pageSize int32, totalPage int32) *GetAccountHoldingResp {
	this := GetAccountHoldingResp{}
	this.TotalNum = totalNum
	this.Items = items
	this.CurrentPage = currentPage
	this.PageSize = pageSize
	this.TotalPage = totalPage
	return &this
}

// NewGetAccountHoldingRespWithDefaults instantiates a new GetAccountHoldingResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetAccountHoldingRespWithDefaults() *GetAccountHoldingResp {
	this := GetAccountHoldingResp{}
	return &this
}

func (o *GetAccountHoldingResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["totalNum"] = o.TotalNum
	toSerialize["items"] = o.Items
	toSerialize["currentPage"] = o.CurrentPage
	toSerialize["pageSize"] = o.PageSize
	toSerialize["totalPage"] = o.TotalPage
	return toSerialize
}

func (o *GetAccountHoldingResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
