// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package earn

// GetAccountHoldingReq struct for GetAccountHoldingReq
type GetAccountHoldingReq struct {
	// currency
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`
	// Product ID
	ProductId *string `json:"productId,omitempty" url:"productId,omitempty"`
	// Product category
	ProductCategory *string `json:"productCategory,omitempty" url:"productCategory,omitempty"`
	// Current request page.
	CurrentPage *int32 `json:"currentPage,omitempty" url:"currentPage,omitempty"`
	// Number of results per request. Minimum is 10, maximum is 500.
	PageSize *int32 `json:"pageSize,omitempty" url:"pageSize,omitempty"`
}

// NewGetAccountHoldingReq instantiates a new GetAccountHoldingReq object
// This constructor will assign default values to properties that have it defined
func NewGetAccountHoldingReq() *GetAccountHoldingReq {
	this := GetAccountHoldingReq{}
	var currentPage int32 = 1
	this.CurrentPage = &currentPage
	var pageSize int32 = 15
	this.PageSize = &pageSize
	return &this
}

// NewGetAccountHoldingReqWithDefaults instantiates a new GetAccountHoldingReq object
// This constructor will only assign default values to properties that have it defined,
func NewGetAccountHoldingReqWithDefaults() *GetAccountHoldingReq {
	this := GetAccountHoldingReq{}
	var currentPage int32 = 1
	this.CurrentPage = &currentPage
	var pageSize int32 = 15
	this.PageSize = &pageSize
	return &this
}

func (o *GetAccountHoldingReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	toSerialize["productId"] = o.ProductId
	toSerialize["productCategory"] = o.ProductCategory
	toSerialize["currentPage"] = o.CurrentPage
	toSerialize["pageSize"] = o.PageSize
	return toSerialize
}

type GetAccountHoldingReqBuilder struct {
	obj *GetAccountHoldingReq
}

func NewGetAccountHoldingReqBuilder() *GetAccountHoldingReqBuilder {
	return &GetAccountHoldingReqBuilder{obj: NewGetAccountHoldingReqWithDefaults()}
}

// currency
func (builder *GetAccountHoldingReqBuilder) SetCurrency(value string) *GetAccountHoldingReqBuilder {
	builder.obj.Currency = &value
	return builder
}

// Product ID
func (builder *GetAccountHoldingReqBuilder) SetProductId(value string) *GetAccountHoldingReqBuilder {
	builder.obj.ProductId = &value
	return builder
}

// Product category
func (builder *GetAccountHoldingReqBuilder) SetProductCategory(value string) *GetAccountHoldingReqBuilder {
	builder.obj.ProductCategory = &value
	return builder
}

// Current request page.
func (builder *GetAccountHoldingReqBuilder) SetCurrentPage(value int32) *GetAccountHoldingReqBuilder {
	builder.obj.CurrentPage = &value
	return builder
}

// Number of results per request. Minimum is 10, maximum is 500.
func (builder *GetAccountHoldingReqBuilder) SetPageSize(value int32) *GetAccountHoldingReqBuilder {
	builder.obj.PageSize = &value
	return builder
}

func (builder *GetAccountHoldingReqBuilder) Build() *GetAccountHoldingReq {
	return builder.obj
}
