// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package earn

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetStakingProductsResp struct for GetStakingProductsResp
type GetStakingProductsResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetStakingProductsData `json:"data,omitempty"`
}

// NewGetStakingProductsResp instantiates a new GetStakingProductsResp object
// This constructor will assign default values to properties that have it defined
func NewGetStakingProductsResp(data []GetStakingProductsData) *GetStakingProductsResp {
	this := GetStakingProductsResp{}
	this.Data = data
	return &this
}

// NewGetStakingProductsRespWithDefaults instantiates a new GetStakingProductsResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetStakingProductsRespWithDefaults() *GetStakingProductsResp {
	this := GetStakingProductsResp{}
	return &this
}

func (o *GetStakingProductsResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetStakingProductsResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetStakingProductsResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
