// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package service

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/internal/interfaces"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/generate/broker/apibroker"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/generate/broker/ndbroker"
)

type BrokerService interface {

	// Get APIBrokerAPI API
	GetAPIBrokerAPI() apibroker.APIBrokerAPI

	// Get NDBrokerAPI API
	GetNDBrokerAPI() ndbroker.NDBrokerAPI
}

type BrokerServiceImpl struct {
	APIBrokerAPI apibroker.APIBrokerAPI
	NDBrokerAPI  ndbroker.NDBrokerAPI
}

func NewBrokerService(transport interfaces.Transport) BrokerService {
	api := &BrokerServiceImpl{}
	api.APIBrokerAPI = apibroker.NewAPIBrokerAPIImp(transport)
	api.NDBrokerAPI = ndbroker.NewNDBrokerAPIImp(transport)
	return api
}

func (impl *BrokerServiceImpl) GetAPIBrokerAPI() apibroker.APIBrokerAPI {
	return impl.APIBrokerAPI
}
func (impl *BrokerServiceImpl) GetNDBrokerAPI() ndbroker.NDBrokerAPI {
	return impl.NDBrokerAPI
}
