// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package service

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/internal/interfaces"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/generate/earn/earn"
)

type EarnService interface {

	// Get EarnAPI API
	GetEarnAPI() earn.EarnAPI
}

type EarnServiceImpl struct {
	EarnAPI earn.EarnAPI
}

func NewEarnService(transport interfaces.Transport) EarnService {
	api := &EarnServiceImpl{}
	api.EarnAPI = earn.NewEarnAPIImp(transport)
	return api
}

func (impl *EarnServiceImpl) GetEarnAPI() earn.EarnAPI {
	return impl.EarnAPI
}
