// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetMarkPriceListResp struct for GetMarkPriceListResp
type GetMarkPriceListResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetMarkPriceListData `json:"data,omitempty"`
}

// NewGetMarkPriceListResp instantiates a new GetMarkPriceListResp object
// This constructor will assign default values to properties that have it defined
func NewGetMarkPriceListResp(data []GetMarkPriceListData) *GetMarkPriceListResp {
	this := GetMarkPriceListResp{}
	this.Data = data
	return &this
}

// NewGetMarkPriceListRespWithDefaults instantiates a new GetMarkPriceListResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetMarkPriceListRespWithDefaults() *GetMarkPriceListResp {
	this := GetMarkPriceListResp{}
	return &this
}

func (o *GetMarkPriceListResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetMarkPriceListResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetMarkPriceListResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
