// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetRecentOrdersListOldResp struct for GetRecentOrdersListOldResp
type GetRecentOrdersListOldResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetRecentOrdersListOldData `json:"data,omitempty"`
}

// NewGetRecentOrdersListOldResp instantiates a new GetRecentOrdersListOldResp object
// This constructor will assign default values to properties that have it defined
func NewGetRecentOrdersListOldResp(data []GetRecentOrdersListOldData) *GetRecentOrdersListOldResp {
	this := GetRecentOrdersListOldResp{}
	this.Data = data
	return &this
}

// NewGetRecentOrdersListOldRespWithDefaults instantiates a new GetRecentOrdersListOldResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetRecentOrdersListOldRespWithDefaults() *GetRecentOrdersListOldResp {
	this := GetRecentOrdersListOldResp{}
	return &this
}

func (o *GetRecentOrdersListOldResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetRecentOrdersListOldResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetRecentOrdersListOldResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
