// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

// CancelOcoOrderByOrderIdReq struct for CancelOcoOrderByOrderIdReq
type CancelOcoOrderByOrderIdReq struct {
	// The unique order id generated by the trading system
	OrderId *string `json:"orderId,omitempty" path:"orderId" url:"-"`
}

// NewCancelOcoOrderByOrderIdReq instantiates a new CancelOcoOrderByOrderIdReq object
// This constructor will assign default values to properties that have it defined
func NewCancelOcoOrderByOrderIdReq() *CancelOcoOrderByOrderIdReq {
	this := CancelOcoOrderByOrderIdReq{}
	return &this
}

// NewCancelOcoOrderByOrderIdReqWithDefaults instantiates a new CancelOcoOrderByOrderIdReq object
// This constructor will only assign default values to properties that have it defined,
func NewCancelOcoOrderByOrderIdReqWithDefaults() *CancelOcoOrderByOrderIdReq {
	this := CancelOcoOrderByOrderIdReq{}
	return &this
}

func (o *CancelOcoOrderByOrderIdReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	return toSerialize
}

type CancelOcoOrderByOrderIdReqBuilder struct {
	obj *CancelOcoOrderByOrderIdReq
}

func NewCancelOcoOrderByOrderIdReqBuilder() *CancelOcoOrderByOrderIdReqBuilder {
	return &CancelOcoOrderByOrderIdReqBuilder{obj: NewCancelOcoOrderByOrderIdReqWithDefaults()}
}

// The unique order id generated by the trading system
func (builder *CancelOcoOrderByOrderIdReqBuilder) SetOrderId(value string) *CancelOcoOrderByOrderIdReqBuilder {
	builder.obj.OrderId = &value
	return builder
}

func (builder *CancelOcoOrderByOrderIdReqBuilder) Build() *CancelOcoOrderByOrderIdReq {
	return builder.obj
}
