// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

// CancelOcoOrderByClientOidReq struct for CancelOcoOrderByClientOidReq
type CancelOcoOrderByClientOidReq struct {
	// Client Order Id，unique identifier created by the user
	ClientOid *string `json:"clientOid,omitempty" path:"clientOid" url:"-"`
}

// NewCancelOcoOrderByClientOidReq instantiates a new CancelOcoOrderByClientOidReq object
// This constructor will assign default values to properties that have it defined
func NewCancelOcoOrderByClientOidReq() *CancelOcoOrderByClientOidReq {
	this := CancelOcoOrderByClientOidReq{}
	return &this
}

// NewCancelOcoOrderByClientOidReqWithDefaults instantiates a new CancelOcoOrderByClientOidReq object
// This constructor will only assign default values to properties that have it defined,
func NewCancelOcoOrderByClientOidReqWithDefaults() *CancelOcoOrderByClientOidReq {
	this := CancelOcoOrderByClientOidReq{}
	return &this
}

func (o *CancelOcoOrderByClientOidReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["clientOid"] = o.ClientOid
	return toSerialize
}

type CancelOcoOrderByClientOidReqBuilder struct {
	obj *CancelOcoOrderByClientOidReq
}

func NewCancelOcoOrderByClientOidReqBuilder() *CancelOcoOrderByClientOidReqBuilder {
	return &CancelOcoOrderByClientOidReqBuilder{obj: NewCancelOcoOrderByClientOidReqWithDefaults()}
}

// Client Order Id，unique identifier created by the user
func (builder *CancelOcoOrderByClientOidReqBuilder) SetClientOid(value string) *CancelOcoOrderByClientOidReqBuilder {
	builder.obj.ClientOid = &value
	return builder
}

func (builder *CancelOcoOrderByClientOidReqBuilder) Build() *CancelOcoOrderByClientOidReq {
	return builder.obj
}
