// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// BatchCancelOcoOrdersResp struct for BatchCancelOcoOrdersResp
type BatchCancelOcoOrdersResp struct {
	// common response
	CommonResponse *types.RestResponse
	// List of two order IDs related to the canceled OCO order
	CancelledOrderIds []string `json:"cancelledOrderIds,omitempty"`
}

// NewBatchCancelOcoOrdersResp instantiates a new BatchCancelOcoOrdersResp object
// This constructor will assign default values to properties that have it defined
func NewBatchCancelOcoOrdersResp(cancelledOrderIds []string) *BatchCancelOcoOrdersResp {
	this := BatchCancelOcoOrdersResp{}
	this.CancelledOrderIds = cancelledOrderIds
	return &this
}

// NewBatchCancelOcoOrdersRespWithDefaults instantiates a new BatchCancelOcoOrdersResp object
// This constructor will only assign default values to properties that have it defined,
func NewBatchCancelOcoOrdersRespWithDefaults() *BatchCancelOcoOrdersResp {
	this := BatchCancelOcoOrdersResp{}
	return &this
}

func (o *BatchCancelOcoOrdersResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["cancelledOrderIds"] = o.CancelledOrderIds
	return toSerialize
}

func (o *BatchCancelOcoOrdersResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
