// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetRecentTradeHistoryOldResp struct for GetRecentTradeHistoryOldResp
type GetRecentTradeHistoryOldResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetRecentTradeHistoryOldData `json:"data,omitempty"`
}

// NewGetRecentTradeHistoryOldResp instantiates a new GetRecentTradeHistoryOldResp object
// This constructor will assign default values to properties that have it defined
func NewGetRecentTradeHistoryOldResp(data []GetRecentTradeHistoryOldData) *GetRecentTradeHistoryOldResp {
	this := GetRecentTradeHistoryOldResp{}
	this.Data = data
	return &this
}

// NewGetRecentTradeHistoryOldRespWithDefaults instantiates a new GetRecentTradeHistoryOldResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetRecentTradeHistoryOldRespWithDefaults() *GetRecentTradeHistoryOldResp {
	this := GetRecentTradeHistoryOldResp{}
	return &this
}

func (o *GetRecentTradeHistoryOldResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetRecentTradeHistoryOldResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetRecentTradeHistoryOldResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
