// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// AddOcoOrderResp struct for AddOcoOrderResp
type AddOcoOrderResp struct {
	// common response
	CommonResponse *types.RestResponse
	// The unique order id generated by the trading system,which can be used later for further actions such as canceling the order.
	OrderId string `json:"orderId,omitempty"`
}

// NewAddOcoOrderResp instantiates a new AddOcoOrderResp object
// This constructor will assign default values to properties that have it defined
func NewAddOcoOrderResp(orderId string) *AddOcoOrderResp {
	this := AddOcoOrderResp{}
	this.OrderId = orderId
	return &this
}

// NewAddOcoOrderRespWithDefaults instantiates a new AddOcoOrderResp object
// This constructor will only assign default values to properties that have it defined,
func NewAddOcoOrderRespWithDefaults() *AddOcoOrderResp {
	this := AddOcoOrderResp{}
	return &this
}

func (o *AddOcoOrderResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	return toSerialize
}

func (o *AddOcoOrderResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
