// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

// BatchAddOrdersSyncData struct for BatchAddOrdersSyncData
type BatchAddOrdersSyncData struct {
	// The unique order id generated by the trading system,which can be used later for further actions such as canceling the order.
	OrderId *string `json:"orderId,omitempty"`
	// The user self-defined order id.
	ClientOid *string `json:"clientOid,omitempty"`
	OrderTime *int64  `json:"orderTime,omitempty"`
	// original order size
	OriginSize *string `json:"originSize,omitempty"`
	// deal size
	DealSize *string `json:"dealSize,omitempty"`
	// remain size
	RemainSize *string `json:"remainSize,omitempty"`
	// Cumulative canceled size
	CanceledSize *string `json:"canceledSize,omitempty"`
	// Order Status. open：order is active; done：order has been completed
	Status    *string `json:"status,omitempty"`
	MatchTime *int64  `json:"matchTime,omitempty"`
	// Add order success/failure
	Success bool `json:"success,omitempty"`
	// error message
	FailMsg *string `json:"failMsg,omitempty"`
}

// NewBatchAddOrdersSyncData instantiates a new BatchAddOrdersSyncData object
// This constructor will assign default values to properties that have it defined
func NewBatchAddOrdersSyncData(success bool) *BatchAddOrdersSyncData {
	this := BatchAddOrdersSyncData{}
	this.Success = success
	return &this
}

// NewBatchAddOrdersSyncDataWithDefaults instantiates a new BatchAddOrdersSyncData object
// This constructor will only assign default values to properties that have it defined,
func NewBatchAddOrdersSyncDataWithDefaults() *BatchAddOrdersSyncData {
	this := BatchAddOrdersSyncData{}
	return &this
}

func (o *BatchAddOrdersSyncData) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	toSerialize["clientOid"] = o.ClientOid
	toSerialize["orderTime"] = o.OrderTime
	toSerialize["originSize"] = o.OriginSize
	toSerialize["dealSize"] = o.DealSize
	toSerialize["remainSize"] = o.RemainSize
	toSerialize["canceledSize"] = o.CanceledSize
	toSerialize["status"] = o.Status
	toSerialize["matchTime"] = o.MatchTime
	toSerialize["success"] = o.Success
	toSerialize["failMsg"] = o.FailMsg
	return toSerialize
}
