// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// BatchAddOrdersSyncResp struct for BatchAddOrdersSyncResp
type BatchAddOrdersSyncResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []BatchAddOrdersSyncData `json:"data,omitempty"`
}

// NewBatchAddOrdersSyncResp instantiates a new BatchAddOrdersSyncResp object
// This constructor will assign default values to properties that have it defined
func NewBatchAddOrdersSyncResp(data []BatchAddOrdersSyncData) *BatchAddOrdersSyncResp {
	this := BatchAddOrdersSyncResp{}
	this.Data = data
	return &this
}

// NewBatchAddOrdersSyncRespWithDefaults instantiates a new BatchAddOrdersSyncResp object
// This constructor will only assign default values to properties that have it defined,
func NewBatchAddOrdersSyncRespWithDefaults() *BatchAddOrdersSyncResp {
	this := BatchAddOrdersSyncResp{}
	return &this
}

func (o *BatchAddOrdersSyncResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *BatchAddOrdersSyncResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *BatchAddOrdersSyncResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
