// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

// GetOcoOrderByClientOidReq struct for GetOcoOrderByClientOidReq
type GetOcoOrderByClientOidReq struct {
	// Client Order Id，unique identifier created by the user
	ClientOid *string `json:"clientOid,omitempty" path:"clientOid" url:"-"`
}

// NewGetOcoOrderByClientOidReq instantiates a new GetOcoOrderByClientOidReq object
// This constructor will assign default values to properties that have it defined
func NewGetOcoOrderByClientOidReq() *GetOcoOrderByClientOidReq {
	this := GetOcoOrderByClientOidReq{}
	return &this
}

// NewGetOcoOrderByClientOidReqWithDefaults instantiates a new GetOcoOrderByClientOidReq object
// This constructor will only assign default values to properties that have it defined,
func NewGetOcoOrderByClientOidReqWithDefaults() *GetOcoOrderByClientOidReq {
	this := GetOcoOrderByClientOidReq{}
	return &this
}

func (o *GetOcoOrderByClientOidReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["clientOid"] = o.ClientOid
	return toSerialize
}

type GetOcoOrderByClientOidReqBuilder struct {
	obj *GetOcoOrderByClientOidReq
}

func NewGetOcoOrderByClientOidReqBuilder() *GetOcoOrderByClientOidReqBuilder {
	return &GetOcoOrderByClientOidReqBuilder{obj: NewGetOcoOrderByClientOidReqWithDefaults()}
}

// Client Order Id，unique identifier created by the user
func (builder *GetOcoOrderByClientOidReqBuilder) SetClientOid(value string) *GetOcoOrderByClientOidReqBuilder {
	builder.obj.ClientOid = &value
	return builder
}

func (builder *GetOcoOrderByClientOidReqBuilder) Build() *GetOcoOrderByClientOidReq {
	return builder.obj
}
