// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// AddStopOrderResp struct for AddStopOrderResp
type AddStopOrderResp struct {
	// common response
	CommonResponse *types.RestResponse
	// The unique order id generated by the trading system,which can be used later for further actions such as canceling the order.
	OrderId string `json:"orderId,omitempty"`
	// The user self-defined order id.
	ClientOid string `json:"clientOid,omitempty"`
}

// NewAddStopOrderResp instantiates a new AddStopOrderResp object
// This constructor will assign default values to properties that have it defined
func NewAddStopOrderResp(orderId string, clientOid string) *AddStopOrderResp {
	this := AddStopOrderResp{}
	this.OrderId = orderId
	this.ClientOid = clientOid
	return &this
}

// NewAddStopOrderRespWithDefaults instantiates a new AddStopOrderResp object
// This constructor will only assign default values to properties that have it defined,
func NewAddStopOrderRespWithDefaults() *AddStopOrderResp {
	this := AddStopOrderResp{}
	return &this
}

func (o *AddStopOrderResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	toSerialize["clientOid"] = o.ClientOid
	return toSerialize
}

func (o *AddStopOrderResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
