// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// CancelStopOrderByOrderIdResp struct for CancelStopOrderByOrderIdResp
type CancelStopOrderByOrderIdResp struct {
	// common response
	CommonResponse *types.RestResponse
	// order id array
	CancelledOrderIds []string `json:"cancelledOrderIds,omitempty"`
}

// NewCancelStopOrderByOrderIdResp instantiates a new CancelStopOrderByOrderIdResp object
// This constructor will assign default values to properties that have it defined
func NewCancelStopOrderByOrderIdResp(cancelledOrderIds []string) *CancelStopOrderByOrderIdResp {
	this := CancelStopOrderByOrderIdResp{}
	this.CancelledOrderIds = cancelledOrderIds
	return &this
}

// NewCancelStopOrderByOrderIdRespWithDefaults instantiates a new CancelStopOrderByOrderIdResp object
// This constructor will only assign default values to properties that have it defined,
func NewCancelStopOrderByOrderIdRespWithDefaults() *CancelStopOrderByOrderIdResp {
	this := CancelStopOrderByOrderIdResp{}
	return &this
}

func (o *CancelStopOrderByOrderIdResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["cancelledOrderIds"] = o.CancelledOrderIds
	return toSerialize
}

func (o *CancelStopOrderByOrderIdResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
