// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetStopOrderByClientOidResp struct for GetStopOrderByClientOidResp
type GetStopOrderByClientOidResp struct {
	// common response
	CommonResponse *types.RestResponse
	// the return code
	Data []GetStopOrderByClientOidData `json:"data,omitempty"`
}

// NewGetStopOrderByClientOidResp instantiates a new GetStopOrderByClientOidResp object
// This constructor will assign default values to properties that have it defined
func NewGetStopOrderByClientOidResp(data []GetStopOrderByClientOidData) *GetStopOrderByClientOidResp {
	this := GetStopOrderByClientOidResp{}
	this.Data = data
	return &this
}

// NewGetStopOrderByClientOidRespWithDefaults instantiates a new GetStopOrderByClientOidResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetStopOrderByClientOidRespWithDefaults() *GetStopOrderByClientOidResp {
	this := GetStopOrderByClientOidResp{}
	return &this
}

func (o *GetStopOrderByClientOidResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetStopOrderByClientOidResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetStopOrderByClientOidResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
