// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package risklimit

// GetMarginRiskLimitReq struct for GetMarginRiskLimitReq
type GetMarginRiskLimitReq struct {
	// true-isolated, false-cross
	IsIsolated *bool `json:"isIsolated,omitempty" url:"isIsolated,omitempty"`
	// currency, This field is only required for cross margin
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`
	// symbol, This field is only required for isolated margin
	Symbol *string `json:"symbol,omitempty" url:"symbol,omitempty"`
}

// NewGetMarginRiskLimitReq instantiates a new GetMarginRiskLimitReq object
// This constructor will assign default values to properties that have it defined
func NewGetMarginRiskLimitReq() *GetMarginRiskLimitReq {
	this := GetMarginRiskLimitReq{}
	return &this
}

// NewGetMarginRiskLimitReqWithDefaults instantiates a new GetMarginRiskLimitReq object
// This constructor will only assign default values to properties that have it defined,
func NewGetMarginRiskLimitReqWithDefaults() *GetMarginRiskLimitReq {
	this := GetMarginRiskLimitReq{}
	return &this
}

func (o *GetMarginRiskLimitReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["isIsolated"] = o.IsIsolated
	toSerialize["currency"] = o.Currency
	toSerialize["symbol"] = o.Symbol
	return toSerialize
}

type GetMarginRiskLimitReqBuilder struct {
	obj *GetMarginRiskLimitReq
}

func NewGetMarginRiskLimitReqBuilder() *GetMarginRiskLimitReqBuilder {
	return &GetMarginRiskLimitReqBuilder{obj: NewGetMarginRiskLimitReqWithDefaults()}
}

// true-isolated, false-cross
func (builder *GetMarginRiskLimitReqBuilder) SetIsIsolated(value bool) *GetMarginRiskLimitReqBuilder {
	builder.obj.IsIsolated = &value
	return builder
}

// currency, This field is only required for cross margin
func (builder *GetMarginRiskLimitReqBuilder) SetCurrency(value string) *GetMarginRiskLimitReqBuilder {
	builder.obj.Currency = &value
	return builder
}

// symbol, This field is only required for isolated margin
func (builder *GetMarginRiskLimitReqBuilder) SetSymbol(value string) *GetMarginRiskLimitReqBuilder {
	builder.obj.Symbol = &value
	return builder
}

func (builder *GetMarginRiskLimitReqBuilder) Build() *GetMarginRiskLimitReq {
	return builder.obj
}
