// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

// GetSubAccountApiListReq struct for GetSubAccountApiListReq
type GetSubAccountApiListReq struct {
	// API-Key
	ApiKey *string `json:"apiKey,omitempty" url:"apiKey,omitempty"`
	// Sub-account name.
	SubName *string `json:"subName,omitempty" url:"subName,omitempty"`
}

// NewGetSubAccountApiListReq instantiates a new GetSubAccountApiListReq object
// This constructor will assign default values to properties that have it defined
func NewGetSubAccountApiListReq() *GetSubAccountApiListReq {
	this := GetSubAccountApiListReq{}
	return &this
}

// NewGetSubAccountApiListReqWithDefaults instantiates a new GetSubAccountApiListReq object
// This constructor will only assign default values to properties that have it defined,
func NewGetSubAccountApiListReqWithDefaults() *GetSubAccountApiListReq {
	this := GetSubAccountApiListReq{}
	return &this
}

func (o *GetSubAccountApiListReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["apiKey"] = o.ApiKey
	toSerialize["subName"] = o.SubName
	return toSerialize
}

type GetSubAccountApiListReqBuilder struct {
	obj *GetSubAccountApiListReq
}

func NewGetSubAccountApiListReqBuilder() *GetSubAccountApiListReqBuilder {
	return &GetSubAccountApiListReqBuilder{obj: NewGetSubAccountApiListReqWithDefaults()}
}

// API-Key
func (builder *GetSubAccountApiListReqBuilder) SetApiKey(value string) *GetSubAccountApiListReqBuilder {
	builder.obj.ApiKey = &value
	return builder
}

// Sub-account name.
func (builder *GetSubAccountApiListReqBuilder) SetSubName(value string) *GetSubAccountApiListReqBuilder {
	builder.obj.SubName = &value
	return builder
}

func (builder *GetSubAccountApiListReqBuilder) Build() *GetSubAccountApiListReq {
	return builder.obj
}
