// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetFuturesSubAccountListV2Resp struct for GetFuturesSubAccountListV2Resp
type GetFuturesSubAccountListV2Resp struct {
	// common response
	CommonResponse *types.RestResponse
	Summary        GetFuturesSubAccountListV2Summary `json:"summary,omitempty"`
	// Account List
	Accounts []GetFuturesSubAccountListV2Accounts `json:"accounts,omitempty"`
}

// NewGetFuturesSubAccountListV2Resp instantiates a new GetFuturesSubAccountListV2Resp object
// This constructor will assign default values to properties that have it defined
func NewGetFuturesSubAccountListV2Resp(summary GetFuturesSubAccountListV2Summary, accounts []GetFuturesSubAccountListV2Accounts) *GetFuturesSubAccountListV2Resp {
	this := GetFuturesSubAccountListV2Resp{}
	this.Summary = summary
	this.Accounts = accounts
	return &this
}

// NewGetFuturesSubAccountListV2RespWithDefaults instantiates a new GetFuturesSubAccountListV2Resp object
// This constructor will only assign default values to properties that have it defined,
func NewGetFuturesSubAccountListV2RespWithDefaults() *GetFuturesSubAccountListV2Resp {
	this := GetFuturesSubAccountListV2Resp{}
	return &this
}

func (o *GetFuturesSubAccountListV2Resp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["summary"] = o.Summary
	toSerialize["accounts"] = o.Accounts
	return toSerialize
}

func (o *GetFuturesSubAccountListV2Resp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
