// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetSpotSubAccountListV1Resp struct for GetSpotSubAccountListV1Resp
type GetSpotSubAccountListV1Resp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetSpotSubAccountListV1Data `json:"data,omitempty"`
}

// NewGetSpotSubAccountListV1Resp instantiates a new GetSpotSubAccountListV1Resp object
// This constructor will assign default values to properties that have it defined
func NewGetSpotSubAccountListV1Resp(data []GetSpotSubAccountListV1Data) *GetSpotSubAccountListV1Resp {
	this := GetSpotSubAccountListV1Resp{}
	this.Data = data
	return &this
}

// NewGetSpotSubAccountListV1RespWithDefaults instantiates a new GetSpotSubAccountListV1Resp object
// This constructor will only assign default values to properties that have it defined,
func NewGetSpotSubAccountListV1RespWithDefaults() *GetSpotSubAccountListV1Resp {
	this := GetSpotSubAccountListV1Resp{}
	return &this
}

func (o *GetSpotSubAccountListV1Resp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetSpotSubAccountListV1Resp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetSpotSubAccountListV1Resp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
