// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

// DeleteSubAccountApiReq struct for DeleteSubAccountApiReq
type DeleteSubAccountApiReq struct {
	// API-Key
	ApiKey *string `json:"apiKey,omitempty" url:"apiKey,omitempty"`
	// Sub-account name.
	SubName *string `json:"subName,omitempty" url:"subName,omitempty"`
	// Password(Password of the API key)
	Passphrase *string `json:"passphrase,omitempty" url:"passphrase,omitempty"`
}

// NewDeleteSubAccountApiReq instantiates a new DeleteSubAccountApiReq object
// This constructor will assign default values to properties that have it defined
func NewDeleteSubAccountApiReq() *DeleteSubAccountApiReq {
	this := DeleteSubAccountApiReq{}
	return &this
}

// NewDeleteSubAccountApiReqWithDefaults instantiates a new DeleteSubAccountApiReq object
// This constructor will only assign default values to properties that have it defined,
func NewDeleteSubAccountApiReqWithDefaults() *DeleteSubAccountApiReq {
	this := DeleteSubAccountApiReq{}
	return &this
}

func (o *DeleteSubAccountApiReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["apiKey"] = o.ApiKey
	toSerialize["subName"] = o.SubName
	toSerialize["passphrase"] = o.Passphrase
	return toSerialize
}

type DeleteSubAccountApiReqBuilder struct {
	obj *DeleteSubAccountApiReq
}

func NewDeleteSubAccountApiReqBuilder() *DeleteSubAccountApiReqBuilder {
	return &DeleteSubAccountApiReqBuilder{obj: NewDeleteSubAccountApiReqWithDefaults()}
}

// API-Key
func (builder *DeleteSubAccountApiReqBuilder) SetApiKey(value string) *DeleteSubAccountApiReqBuilder {
	builder.obj.ApiKey = &value
	return builder
}

// Sub-account name.
func (builder *DeleteSubAccountApiReqBuilder) SetSubName(value string) *DeleteSubAccountApiReqBuilder {
	builder.obj.SubName = &value
	return builder
}

// Password(Password of the API key)
func (builder *DeleteSubAccountApiReqBuilder) SetPassphrase(value string) *DeleteSubAccountApiReqBuilder {
	builder.obj.Passphrase = &value
	return builder
}

func (builder *DeleteSubAccountApiReqBuilder) Build() *DeleteSubAccountApiReq {
	return builder.obj
}
