// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// AddSubAccountApiResp struct for AddSubAccountApiResp
type AddSubAccountApiResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Sub-account name
	SubName string `json:"subName,omitempty"`
	// Remarks
	Remark string `json:"remark,omitempty"`
	// API Key
	ApiKey string `json:"apiKey,omitempty"`
	// API Secret Key
	ApiSecret string `json:"apiSecret,omitempty"`
	// API Version
	ApiVersion int32 `json:"apiVersion,omitempty"`
	// Password
	Passphrase string `json:"passphrase,omitempty"`
	// [Permissions](doc://link/pages/338144)
	Permission string `json:"permission,omitempty"`
	// IP whitelist
	IpWhitelist *string `json:"ipWhitelist,omitempty"`
	// Time of the event
	CreatedAt int64 `json:"createdAt,omitempty"`
}

// NewAddSubAccountApiResp instantiates a new AddSubAccountApiResp object
// This constructor will assign default values to properties that have it defined
func NewAddSubAccountApiResp(subName string, remark string, apiKey string, apiSecret string, apiVersion int32, passphrase string, permission string, createdAt int64) *AddSubAccountApiResp {
	this := AddSubAccountApiResp{}
	this.SubName = subName
	this.Remark = remark
	this.ApiKey = apiKey
	this.ApiSecret = apiSecret
	this.ApiVersion = apiVersion
	this.Passphrase = passphrase
	this.Permission = permission
	this.CreatedAt = createdAt
	return &this
}

// NewAddSubAccountApiRespWithDefaults instantiates a new AddSubAccountApiResp object
// This constructor will only assign default values to properties that have it defined,
func NewAddSubAccountApiRespWithDefaults() *AddSubAccountApiResp {
	this := AddSubAccountApiResp{}
	return &this
}

func (o *AddSubAccountApiResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["subName"] = o.SubName
	toSerialize["remark"] = o.Remark
	toSerialize["apiKey"] = o.ApiKey
	toSerialize["apiSecret"] = o.ApiSecret
	toSerialize["apiVersion"] = o.ApiVersion
	toSerialize["passphrase"] = o.Passphrase
	toSerialize["permission"] = o.Permission
	toSerialize["ipWhitelist"] = o.IpWhitelist
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize
}

func (o *AddSubAccountApiResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
