// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

import (
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// ModifySubAccountApiResp struct for ModifySubAccountApiResp
type ModifySubAccountApiResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Sub-account name
	SubName string `json:"subName,omitempty"`
	// API Key
	ApiKey string `json:"apiKey,omitempty"`
	// [Permissions](https://www.kucoin.com/docs-new/doc-338144)
	Permission string `json:"permission,omitempty"`
	// IP whitelist
	IpWhitelist *string `json:"ipWhitelist,omitempty"`
}

// NewModifySubAccountApiResp instantiates a new ModifySubAccountApiResp object
// This constructor will assign default values to properties that have it defined
func NewModifySubAccountApiResp(subName string, apiKey string, permission string) *ModifySubAccountApiResp {
	this := ModifySubAccountApiResp{}
	this.SubName = subName
	this.ApiKey = apiKey
	this.Permission = permission
	return &this
}

// NewModifySubAccountApiRespWithDefaults instantiates a new ModifySubAccountApiResp object
// This constructor will only assign default values to properties that have it defined,
func NewModifySubAccountApiRespWithDefaults() *ModifySubAccountApiResp {
	this := ModifySubAccountApiResp{}
	return &this
}

func (o *ModifySubAccountApiResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["subName"] = o.SubName
	toSerialize["apiKey"] = o.ApiKey
	toSerialize["permission"] = o.Permission
	toSerialize["ipWhitelist"] = o.IpWhitelist
	return toSerialize
}

func (o *ModifySubAccountApiResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
