// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package account

// GetIsolatedMarginAccountDetailV1BaseAsset base asset
type GetIsolatedMarginAccountDetailV1BaseAsset struct {
	// currency
	Currency string `json:"currency,omitempty"`
	// Current currency total asset amount
	TotalBalance string `json:"totalBalance,omitempty"`
	// Current currency holding asset amount
	HoldBalance string `json:"holdBalance,omitempty"`
	// Current available asset amount
	AvailableBalance string `json:"availableBalance,omitempty"`
	// Liabilities
	Liability        string `json:"liability,omitempty"`
	Interest         string `json:"interest,omitempty"`
	BorrowableAmount string `json:"borrowableAmount,omitempty"`
}

// NewGetIsolatedMarginAccountDetailV1BaseAsset instantiates a new GetIsolatedMarginAccountDetailV1BaseAsset object
// This constructor will assign default values to properties that have it defined
func NewGetIsolatedMarginAccountDetailV1BaseAsset(currency string, totalBalance string, holdBalance string, availableBalance string, liability string, interest string, borrowableAmount string) *GetIsolatedMarginAccountDetailV1BaseAsset {
	this := GetIsolatedMarginAccountDetailV1BaseAsset{}
	this.Currency = currency
	this.TotalBalance = totalBalance
	this.HoldBalance = holdBalance
	this.AvailableBalance = availableBalance
	this.Liability = liability
	this.Interest = interest
	this.BorrowableAmount = borrowableAmount
	return &this
}

// NewGetIsolatedMarginAccountDetailV1BaseAssetWithDefaults instantiates a new GetIsolatedMarginAccountDetailV1BaseAsset object
// This constructor will only assign default values to properties that have it defined,
func NewGetIsolatedMarginAccountDetailV1BaseAssetWithDefaults() *GetIsolatedMarginAccountDetailV1BaseAsset {
	this := GetIsolatedMarginAccountDetailV1BaseAsset{}
	return &this
}

func (o *GetIsolatedMarginAccountDetailV1BaseAsset) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	toSerialize["totalBalance"] = o.TotalBalance
	toSerialize["holdBalance"] = o.HoldBalance
	toSerialize["availableBalance"] = o.AvailableBalance
	toSerialize["liability"] = o.Liability
	toSerialize["interest"] = o.Interest
	toSerialize["borrowableAmount"] = o.BorrowableAmount
	return toSerialize
}
