// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package transfer

// FuturesAccountTransferOutReq struct for FuturesAccountTransferOutReq
type FuturesAccountTransferOutReq struct {
	// Currency, including XBT,USDT...
	Currency string `json:"currency,omitempty"`
	// Amount to be transfered out, the maximum cannot exceed 1000000000
	Amount float32 `json:"amount,omitempty"`
	// Receive account type, including MAIN,TRADE
	RecAccountType string `json:"recAccountType,omitempty"`
}

// NewFuturesAccountTransferOutReq instantiates a new FuturesAccountTransferOutReq object
// This constructor will assign default values to properties that have it defined
func NewFuturesAccountTransferOutReq(currency string, amount float32, recAccountType string) *FuturesAccountTransferOutReq {
	this := FuturesAccountTransferOutReq{}
	this.Currency = currency
	this.Amount = amount
	this.RecAccountType = recAccountType
	return &this
}

// NewFuturesAccountTransferOutReqWithDefaults instantiates a new FuturesAccountTransferOutReq object
// This constructor will only assign default values to properties that have it defined,
func NewFuturesAccountTransferOutReqWithDefaults() *FuturesAccountTransferOutReq {
	this := FuturesAccountTransferOutReq{}
	return &this
}

func (o *FuturesAccountTransferOutReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	toSerialize["amount"] = o.Amount
	toSerialize["recAccountType"] = o.RecAccountType
	return toSerialize
}

type FuturesAccountTransferOutReqBuilder struct {
	obj *FuturesAccountTransferOutReq
}

func NewFuturesAccountTransferOutReqBuilder() *FuturesAccountTransferOutReqBuilder {
	return &FuturesAccountTransferOutReqBuilder{obj: NewFuturesAccountTransferOutReqWithDefaults()}
}

// Currency, including XBT,USDT...
func (builder *FuturesAccountTransferOutReqBuilder) SetCurrency(value string) *FuturesAccountTransferOutReqBuilder {
	builder.obj.Currency = value
	return builder
}

// Amount to be transfered out, the maximum cannot exceed 1000000000
func (builder *FuturesAccountTransferOutReqBuilder) SetAmount(value float32) *FuturesAccountTransferOutReqBuilder {
	builder.obj.Amount = value
	return builder
}

// Receive account type, including MAIN,TRADE
func (builder *FuturesAccountTransferOutReqBuilder) SetRecAccountType(value string) *FuturesAccountTransferOutReqBuilder {
	builder.obj.RecAccountType = value
	return builder
}

func (builder *FuturesAccountTransferOutReqBuilder) Build() *FuturesAccountTransferOutReq {
	return builder.obj
}
