// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package transfer

import (
	"encoding/json"
	"github.com/Kucoin/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// FuturesAccountTransferInResp struct for FuturesAccountTransferInResp
type FuturesAccountTransferInResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           string `json:"data,omitempty"`
}

// NewFuturesAccountTransferInResp instantiates a new FuturesAccountTransferInResp object
// This constructor will assign default values to properties that have it defined
func NewFuturesAccountTransferInResp(data string) *FuturesAccountTransferInResp {
	this := FuturesAccountTransferInResp{}
	this.Data = data
	return &this
}

// NewFuturesAccountTransferInRespWithDefaults instantiates a new FuturesAccountTransferInResp object
// This constructor will only assign default values to properties that have it defined,
func NewFuturesAccountTransferInRespWithDefaults() *FuturesAccountTransferInResp {
	this := FuturesAccountTransferInResp{}
	return &this
}

func (o *FuturesAccountTransferInResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *FuturesAccountTransferInResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *FuturesAccountTransferInResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
